spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Json@123
    url: jdbc:mysql://47.102.207.194/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell

weChat:
  mpAppId: wxe1a5beeea0aa2c38
  mpAppSecret: 3aefa3a16030c76737c09e50bf137375
  mchId: 1
  mchKey: 2
  keyPath: 3
  notifyUrl: http://json666.natapp1.cc/sell/pay/notify