spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Json@123
    url: jdbc:mysql://47.102.207.194/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell